version: '3.8'

services:
  app:
    build: .
    container_name: url-shortener
    environment:
      CONFIG_PATH: "/app/config/local.yaml"
    ports:
      - "8082:8082"
    volumes:
      - ./migrations:/app/migrations
    depends_on:
      postgres:
        condition: service_healthy


  postgres:
    image: postgres:15-alpine
    container_name: url_shortener_db
    environment:
      POSTGRES_USER: "shortener"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
      POSTGRES_DB: "shortener"
    ports:
        - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U shortener -d shortener -t 1"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: